fixed toolchain

diff --git a/src/configure_android_armv7 b/src/configure_android_armv7
--- a/src/configure_android_armv7
+++ b/src/configure_android_armv7
@@ -6,6 +6,17 @@ ANDROID_SDK=/opt/android-sdk
 ANDROID_NDK=/opt/android-ndk
 export ANDROID_SDK
 export ANDROID_NDK
+TOOLCHAIN=/opt/android-toolchain
+
+if [ ! -d "$ANDROID_SDK" ];then
+    echo "Android SDK not found in $ANDROID_SDK"
+    exit 1
+fi
+
+if [ ! -d "$TOOLCHAIN" ];then
+    echo "Android toolchain not found in $TOOLCHAIN"
+    exit 1
+fi
 
 if [ ! -d release ]
 then
@@ -22,4 +33,4 @@ else
 fi
 
 cd release
-cmake ../HuggleLite -DCMAKE_PREFIX_PATH="$q" -DCMAKE_TOOLCHAIN_FILE=../../deps/qt-android-cmake/toolchain/android.toolchain.cmake
+cmake ../HuggleLite -DANDROID_STANDALONE_TOOLCHAIN=/opt/android-toolchain -DCMAKE_PREFIX_PATH="$q" -DCMAKE_TOOLCHAIN_FILE=../../deps/qt-android-cmake/toolchain/android.toolchain.cmake
